export default [
  {
    title:'首页',
    key:'/admin/home'
  },
  {
    title:'UI',
    key:'/admin/ui',
    children:[
      {
        title:'按钮',
        key:'/admin/ui/bottons'
      },
      {
        title:'弹框',
        key:'/admin/ui/modals'
      },
      {
        title:'Loading',
        key:'/admin/ui/Loading'
      },
      {
        title:'通知提醒',
        key:'/admin/ui/notification'
      },
      {
        title:'图片画廊',
        key:'/admin/ui/gallery'
      },
      {
        title:'轮播图',
        key:'/admin/ui/carousel'
      }
    ]
  },
  {
    title:'表单',
    key:'/admin/form',
    children:[
      {
        title:'登录',
        key:'/admin/form/login'
      },
      {
        title:'注册',
        key:'/admin/ui/reg'
      }
    ]
  },
  {
    title:'表格',
    key:'/admin/admin/table',
    children:[
      {
        title:'基础表格',
        key:'/admin/table/basic'
      },
      {
        title:'高级表格',
        key:'/admin/table/high'
      }
    ]
  },
  {
    title:'富文本',
    key:'/admin/rich'
  },
  {
    title:'城市管理',
    key:'/admin/city'
  },
  {
    title:'员工管理',
    key:'/admin/user'
  },
  {
    title:'车辆管理',
    key:'/admin/bikeMap'
  },
  {
    title:'图标',
    key:'/admin/charts',
    children:[
      {
        title:'柱形图',
        key:'/admin/charts/bar'
      },
      {
        title:'饼图',
        key:'/admin/charts/pie'
      },
      {
        title:'折线图',
        key:'/admin/charts/line'
      },
    ]
  },
  {
    title:'权限设置',
    key:'/admin/permission'
  }
]